services:
  web:
    restart: always
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes: 
      - ./web:/code
    command: "gunicorn django_test_app.wsgi:application -w 2 -b :8000"